### ISSUE TITLE
File name too long when general-links has a lot of categories

### ISSUE THREAD

**Issue by volkanunsal** [codeforamerica/ohana-web-search#743]
It comes from here. 

```haml
# _homepage-links.html.haml
- cache ['general-links', *general_links] do
```

**Comment by anselmbradford** [comment]
Thanks @volkanunsal! Is this throwing an error? Do you have an example of how to reproduce it?

**Comment by volkanunsal** [comment]
The best way to reproduce is to add more than a hundred categories into the settings.yml and watch it burn.

**Comment by monfresh** [comment]
Thanks for the bug report! I would consider that an edge case and I would not recommend having that many categories on the homepage. I believe it would lead to a poor UX to have to read through that much text on the home page.

That said, the reason why this is happening is because the cache key is generated from the list of categories. The more categories, the longer the cache key name, until it gets too long. There are several ways to fix this:

1. Disable fragment caching by default and leave it up to each deployment to decide whether or not they need to cache the categories.

2. Fix it by creating an MD5 digest of the category names to reduce the length of the cache key, like this:
```ruby
- cache ['general-links', Digest::MD5.hexdigest(general_links.to_s)] do
```
Same with the emergency links.

**Comment by volkanunsal** [comment]
That should work. Thanks!

**Comment by monfresh** [comment]
Reopening since we need to fix this.
