### ISSUE TITLE
Services map should show all services

### ISSUE THREAD

**Issue by devinbalkind** [codeforamerica/ohana-web-search#784]
I have a service category with 35 services in it.  

http://services.nycprepared.org/locations?keyword=Mental+Health+%26+Crisis+Counseling

Due to Ohana Web Search pagination, it's divided into two pages: one of 30 services and the other with 5.  The first page has the 30 services on it's map.  The second page has five services mapped.

When a user is looking at a service category, they want to see the location of all services. Dividing that location information between pages is confusing.  Thus, I think the map on both pages should contain all services in that category.  

An additional feature that might improve usability would be, when a user hovers over a service card below the map, to highlight that service on the map.

Thanks for the Ohana Web Search app.  It's very useful!

**Comment by anselmbradford** [comment]
> Due to Ohana Web Search pagination, it's divided into two pages: one of 30 services and the other with 5. The first page has the 30 services on it's map. The second page has five services mapped.

There is a per_page parameter that can be added, e.g. 
http://services.nycprepared.org/locations?keyword=Mental+Health+%26+Crisis+Counseling&per_page=35, perhaps that should live as a setting in https://github.com/codeforamerica/ohana-web-search/blob/master/config/settings.yml

> An additional feature that might improve usability would be, when a user hovers over a service card below the map, to highlight that service on the map.

Mm, I agree this and the reverse as well would be a cool feature to have. User testing actually indicated the map wasn't useful to have at two sizes, so having only one size and a show/hide instead of min/max would simplify the map logic and make it easier to implement something like this.

> Thanks for the Ohana Web Search app. It's very useful!

Thanks for making use of it!

**Comment by devinbalkind** [comment]
On Wed, Mar 4, 2015 at 8:01 PM, Ans <notifications@github.com> wrote:

> Due to Ohana Web Search pagination, it's divided into two pages: one of 30
> services and the other with 5. The first page has the 30 services on it's
> map. The second page has five services mapped.
>
> There is a per_page parameter that can be added, e.g.
>
> http://services.nycprepared.org/locations?keyword=Mental+Health+%26+Crisis+Counseling&per_page=35,
> perhaps that should live as a setting in
> https://github.com/codeforamerica/ohana-web-search/blob/master/config/settings.yml
>
I think making it a setting is a good idea.


>  An additional feature that might improve usability would be, when a user
> hovers over a service card below the map, to highlight that service on the
> map.
>
> Mm, I agree this and the reverse as well would be a cool feature to have.
>

Agreed


> User testing actually indicated the map wasn't useful to have at two
> sizes, so having only one size and a show/hide instead of min/max would
> simplify the map logic and make it easier to implement something like this.
>

I agree.  Make the big map the default.  People love maps.


>  Thanks for the Ohana Web Search app. It's very useful!
>
> Thanks for making use of it!
>

Certainly easier to use than it is to make. :)

**Comment by monfresh** [comment]
Hi @devinbalkind. Thanks for your feedback.

The API is configured to return 30 results at a time by default for performance reasons. The more results returned, the slower the API takes to respond, and the slower the information appears on the website for the user, and the more frustrated the user becomes. This performance is especially important for those who might be using the site on a mobile device over a slow cellular network.

If I'm understanding the issue correctly, you want the map to always show the total number of results, whether that number is 30, 35, 100, or 1000, correct? For performance reasons, the API only allows up to 100 results to be returned at a time. So, making the `per_page` parameter a setting will not solve your problem unless your data contains less than 100 locations. This max number can be adjusted in the API app, but I would not recommend making it higher unless you're confident that your server can handle the load and maintain a fast-loading website. I would also not recommend setting the `per_page` to 100 by default.

Splitting up results into multiple pages is very common on the internet. Take Airbnb for example. When you do a search that has 1000+ results, they don't show you every single 1000+ results on the map. They show you a portion of the results, and when you go to the next page of results, the map updates to reflect this new set of results.

Furthermore, the usability testing that Jared Vorkavich conducted revealed that "few participants used the maps to locate services without being prompted."

Also:
>Transportation is a substantial limiting factor for many Help Seekers. While some participants did have access to a car, most relied on public transit. Participants could generally determine if a service was within their transportation means by reading the street address. Maps were not very important because the participants were very familiar with the area. Including public transit information on the site is helpful, but not essential.

Making the `per_page` parameter a global setting would imply that we've vetted setting it to any arbitrary number, but we have not. Performance testing would need to happen to determine whether a particular number works, and that would depend on where and how you've deployed the app, and on how many visitors you expect and what kind of internet connection they will be on.

One thing we could add is a way to let the user pick how many results they want to see at a time, but based on the user research, no one would use it since no one has mentioned this as an issue so far except for you. When you say "When a user is looking at a service category, they want to see the location of all services", was that based on you observing people use your site, or is this just your personal opinion?

**Comment by devinbalkind** [comment]
On Sat, Mar 7, 2015 at 1:52 PM, Moncef Belyamani <notifications@github.com>
wrote:

> Hi @devinbalkind <https://github.com/devinbalkind>. Thanks for your
> feedback.
>
> The API is configured to return 30 results at a time by default for
> performance reasons. The more results returned, the slower the API takes to
> respond, and the slower the information appears on the website for the
> user, and the more frustrated the user becomes. This performance is
> especially important for those who might be using the site on a mobile
> device over a slow cellular network.
>

Understood.


> If I'm understanding the issue correctly, you want the map to always show
> the total number of results, whether that number is 30, 35, 100, or 1000,
> correct? For performance reasons, the API only allows up to 100 results to
> be returned at a time. So, making the per_page parameter a setting will
> not solve your problem unless your data contains less than 100 locations.
> This max number can be adjusted in the API app, but I would not recommend
> making it higher unless you're confident that your server can handle the
> load and maintain a fast-loading website. I would also not recommend
> setting the per_page to 100 by default.
>
Gotcha.

> Splitting up results into multiple pages is very common on the internet.
> Take Airbnb for example. When you do a search that has 1000+ results, they
> don't show you every single 1000+ results on the map. They show you a
> portion of the results, and when you go to the next page of results, the
> map updates to reflect this new set of results.
>
I like how some maps clump pins together and give you a quantity of
locations.  (example image attached) from here:
http://data.nycprepared.org/dataset/senior-center-directory/resource/4b404d6a-fa67-47b9-8033-b98f81f3dcb0

> Furthermore, the usability testing that Jared Vorkavich conducted revealed
> that "few participants used the maps to locate services without being
> prompted."
>

If the map were large I bet more people would use it.


> Also:
>
> Transportation is a substantial limiting factor for many Help Seekers.
> While some participants did have access to a car, most relied on public
> transit. Participants could generally determine if a service was within
> their transportation means by reading the street address. Maps were not
> very important because the participants were very familiar with the area.
> Including public transit information on the site is helpful, but not
> essential.
>
>
Interesting.  I believe it.  My use case is a bit different.  It's for case
managers who want to make referrals to people.  Many of these are disaster
case managers (DCMs) with limited local knowledge.  I think maps would help
them.  We also want to show resource planners where service are available
so they can see gaps, etc.


>  Making the per_page parameter a global setting would imply that we've
> vetted setting it to any arbitrary number, but we have not. Performance
> testing would need to happen to determine whether a particular number
> works, and that would depend on where and how you've deployed the app, and
> on how many visitors you expect and what kind of internet connection they
> will be on.
>
I like pagination.  Sites like Yelp make that pagination based on relevance
(ratings, location, open, etc) which is cool.  If there was an explicit
pagination logic, maybe alphabetic by service name or organization, that
might make this seem less random.


> One thing we could add is a way to let the user pick how many results they
> want to see at a time, but based on the user research, no one would use it
> since no one has mentioned this as an issue so far except for you. When you
> say "When a user is looking at a service category, they want to see the
> location of all services", was that based on you observing people use your
> site, or is this just your personal opinion?
>

It's an assumption, but one that I think is implicit in the act of clicking
on something. I certainly don't think  that a user is looking for a random
selection of services within that category.  If there were sort
functionality, such as by location, alphabetically, recently updated, etc
then I think we could/should discuss what a user would want to do other
than seeing all results.

**Comment by monfresh** [comment]
Search results in Ohana Web Search that contain the `keyword` parameter are certainly not random. They are based on relevance according to a specific formula, as mentioned in the [search documentation](http://codeforamerica.github.io/ohana-api-docs/#get-locations-that-match-certain-criteria-). As long as the data hasn't changed, performing the same search multiple times should always return the same results in the same order. I would be quite surprised if your results were truly random.

If your keyword searches are not being sorted by the relevance you expect, it's either because your data is incomplete or incorrect, or because your particular use case might require a different formula.

In order to restrict a search to a location, you can add the `location` parameter to the search, and those results will automatically be sorted by distance from the location parameter, with the closest ones first. 

The use cases with large maps such as for resource planners are definitely valid and important, but those are better suited for a different type of application. Resource planners are most likely more interested in a bird's eye view of all services as opposed to performing various keyword searches. For them, a map created with a service like [CartoDB](http://cartodb.com/) would probably be a better solution.

**Comment by devinbalkind** [comment]
Sorry - I should be careful with my use of the term "random".  What I meant
was that the results don't appear to be organized in any specific way.

I haven't done usability tests but I imagine a significant percentage of
users browse services by clicking on the categories on the front page,
which then give them a series of results with no clear sorting logic. But
that's not the point of my issue.

I'm simply suggesting that the map could have a representation of the total
amount of services available for any given search.

**Comment by monfresh** [comment]
> Sorry - I should be careful with my use of the term "random".  What I meant
was that the results don't appear to be organized in any specific way.

>I haven't done usability tests but I imagine a significant percentage of
users browse services by clicking on the categories on the front page,
which then give them a series of results with no clear sorting logic. But
that's not the point of my issue.

But they *do* have a sorting logic, and are organized in a very specific way. They are sorted by relevance, which is how most people using keyword-based searches on the internet expect results to be sorted, no?

>I'm simply suggesting that the map could have a representation of the total
amount of services available for any given search.

Understood. Unfortunately, we cannot implement this in the generic version of the API because it would negatively impact the performance of deployments with large data sets, and who might not even want this feature.

I personally don't see the value of showing all results on the map from the help seeker's or referrer's perspective. The goal in a typical search is to narrow down the results, not to see every single result. Most people will want to see results in a particular location. They're not interested in going to a service that they can't get to, or that might not serve their ZIP code.

Jared's research also has shown that people value quality over quantity:

>Participants often spent the most time reviewing the first few listings and then quickly skimmed the rest of the page. Only one participant in the study reviewed results beyond those listed on the first page. This suggests that a high priority should be placed ensuring the relevance of the first few results, and that there is little advantage to returning a large number of results. 

In an early version of the API, we used to do an `OR` based search when the `keyword` parameter contained more than one word, and our users actually complained that too many results were being returned. We then switched to an `AND` based search which resulted in more relevant results.

By linking the pins on the map to the list results, it makes it clear which locations are on the map. If every single result were shown at once on the map, it would be hard to know which ones are the most relevant. Highlighting a pin when you hover over a list result could help, but if most people only look at the first few results, why even bother showing the less relevant results on the map?

I encourage you to read [Jared's full report](https://docs.google.com/a/codeforamerica.org/document/d/1UADhAQ8_tW7_QjrEHVh8AQ49S-t-3LD5Jg0hxb9wEf4/edit#).
